name: CI tests
on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  # cancels running checks on new pushes
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pytest:
    name: Run Python unit tests
    # Note that 20.04 is currently required until galvani supports mdbtools>=1.0.
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install MDBTools OS dependency
        run: |
          sudo apt install -y mdbtools

      # tox-gh workflow following instructions at https://github.com/tox-dev/tox-gh
      - name: Install tox
        run: python -m pip install tox-gh

      - name: Setup tests
        run: |
          tox -vv --notest

      - name: Run all tests
        run: |
          tox --skip-pkg-install
