# SPDX-FileCopyrightText: 2013-2020 Christopher Kerr, "bcolsen"
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI tests
on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  # cancels running checks on new pushes
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pytest:
    name: Run Python unit tests
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Cached LFS checkout
        uses: nschloe/action-cached-lfs-checkout@v1.2.2
        with:
          fetch-depth: 0
          enableCrossOsArchive: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install MDBTools OS dependency
        run: |
          sudo apt install -y mdbtools

      # tox-gh workflow following instructions at https://github.com/tox-dev/tox-gh
      - name: Install tox
        run: python -m pip install tox-gh

      - name: Setup tests
        run: |
          tox -vv --notest

      - name: Run all tests
        run: |
          tox --skip-pkg-install
